<?php

declare(strict_types=1);
/**
 * fincode API.
 *
 * fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Fincode\Model;

use OpenAPI\Fincode\ObjectSerializer;

/**
 * 上書き顧客（請求先）情報\\ &#x60;customer_id&#x60;で指定した顧客の情報のうち、上書きを行う場合に指定します。\\ 顧客情報の上書きはこのインボイス情報においてのみ適用されます。
 *
 * @implements \ArrayAccess<string, mixed>
 */
class InvoiceCreatingRequestCustomerOverwrite implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    protected static string $openAPIModelName = 'Invoice_Creating_Request_customer_overwrite';
    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = ['name' => 'string', 'email' => 'string', 'addrCountry' => 'string', 'addrState' => 'string', 'addrCity' => 'string', 'addrLine1' => 'string', 'addrLine2' => 'string', 'addrLine3' => 'string', 'addrPostCode' => 'string'];
    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = ['name' => null, 'email' => null, 'addrCountry' => null, 'addrState' => null, 'addrCity' => null, 'addrLine1' => null, 'addrLine2' => null, 'addrLine3' => null, 'addrPostCode' => null];
    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = ['name' => false, 'email' => false, 'addrCountry' => false, 'addrState' => false, 'addrCity' => false, 'addrLine1' => false, 'addrLine2' => false, 'addrLine3' => false, 'addrPostCode' => false];
    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array<string, string|null>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties.
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = ['name' => 'name', 'email' => 'email', 'addrCountry' => 'addr_country', 'addrState' => 'addr_state', 'addrCity' => 'addr_city', 'addrLine1' => 'addr_line_1', 'addrLine2' => 'addr_line_2', 'addrLine3' => 'addr_line_3', 'addrPostCode' => 'addr_post_code'];
    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var array<string, string>
     */
    protected static array $setters = ['name' => 'setName', 'email' => 'setEmail', 'addrCountry' => 'setAddrCountry', 'addrState' => 'setAddrState', 'addrCity' => 'setAddrCity', 'addrLine1' => 'setAddrLine1', 'addrLine2' => 'setAddrLine2', 'addrLine3' => 'setAddrLine3', 'addrPostCode' => 'setAddrPostCode'];
    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var array<string, string>
     */
    protected static array $getters = ['name' => 'getName', 'email' => 'getEmail', 'addrCountry' => 'getAddrCountry', 'addrState' => 'getAddrState', 'addrCity' => 'getAddrCity', 'addrLine1' => 'getAddrLine1', 'addrLine2' => 'getAddrLine2', 'addrLine3' => 'getAddrLine3', 'addrPostCode' => 'getAddrPostCode'];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }
    /**
     * Associative array for storing property values.
     *
     * @phpstan-var array<string, mixed>
     *
     * @psalm-var array<string, mixed>
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param array<string, mixed> $data Associated array of property values
     *                                   initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('addrCountry', $data ?? [], null);
        $this->setIfExists('addrState', $data ?? [], null);
        $this->setIfExists('addrCity', $data ?? [], null);
        $this->setIfExists('addrLine1', $data ?? [], null);
        $this->setIfExists('addrLine2', $data ?? [], null);
        $this->setIfExists('addrLine3', $data ?? [], null);
        $this->setIfExists('addrPostCode', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }
        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return list<string> invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];
        if (!is_null($this->container['name']) && mb_strlen($this->container['name']) > 384) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 384.";
        }
        if (!is_null($this->container['email']) && mb_strlen($this->container['email']) > 254) {
            $invalidProperties[] = "invalid value for 'email', the character length must be smaller than or equal to 254.";
        }
        if (!is_null($this->container['addrCountry']) && mb_strlen($this->container['addrCountry']) > 3) {
            $invalidProperties[] = "invalid value for 'addrCountry', the character length must be smaller than or equal to 3.";
        }
        if (!is_null($this->container['addrState']) && mb_strlen($this->container['addrState']) > 3) {
            $invalidProperties[] = "invalid value for 'addrState', the character length must be smaller than or equal to 3.";
        }
        if (!is_null($this->container['addrCity']) && mb_strlen($this->container['addrCity']) > 50) {
            $invalidProperties[] = "invalid value for 'addrCity', the character length must be smaller than or equal to 50.";
        }
        if (!is_null($this->container['addrLine1']) && mb_strlen($this->container['addrLine1']) > 50) {
            $invalidProperties[] = "invalid value for 'addrLine1', the character length must be smaller than or equal to 50.";
        }
        if (!is_null($this->container['addrLine2']) && mb_strlen($this->container['addrLine2']) > 50) {
            $invalidProperties[] = "invalid value for 'addrLine2', the character length must be smaller than or equal to 50.";
        }
        if (!is_null($this->container['addrLine3']) && mb_strlen($this->container['addrLine3']) > 50) {
            $invalidProperties[] = "invalid value for 'addrLine3', the character length must be smaller than or equal to 50.";
        }
        if (!is_null($this->container['addrPostCode']) && mb_strlen($this->container['addrPostCode']) > 16) {
            $invalidProperties[] = "invalid value for 'addrPostCode', the character length must be smaller than or equal to 16.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): mixed
    {
        return $this->container['name'];
    }

    /**
     * Sets name.
     *
     * @param string $name 上書き顧客（請求先）宛名
     */
    public function setName(mixed $name): static
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if (mb_strlen($name) > 384) {
            throw new \InvalidArgumentException('invalid length for $name when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 384.');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): mixed
    {
        return $this->container['email'];
    }

    /**
     * Sets email.
     *
     * @param string $email 上書き顧客（請求先）メールアドレス
     */
    public function setEmail(mixed $email): static
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        if (mb_strlen($email) > 254) {
            throw new \InvalidArgumentException('invalid length for $email when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 254.');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets addrCountry.
     *
     * @return string|null
     */
    public function getAddrCountry(): mixed
    {
        return $this->container['addrCountry'];
    }

    /**
     * Sets addrCountry.
     *
     * @param string $addrCountry 上書き顧客（請求先）住所の国コード
     */
    public function setAddrCountry(mixed $addrCountry): static
    {
        if (is_null($addrCountry)) {
            throw new \InvalidArgumentException('non-nullable addrCountry cannot be null');
        }
        if (mb_strlen($addrCountry) > 3) {
            throw new \InvalidArgumentException('invalid length for $addrCountry when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 3.');
        }
        $this->container['addrCountry'] = $addrCountry;

        return $this;
    }

    /**
     * Gets addrState.
     *
     * @return string|null
     */
    public function getAddrState(): mixed
    {
        return $this->container['addrState'];
    }

    /**
     * Sets addrState.
     *
     * @param string $addrState 上書き顧客（請求先） 住所の都道府県コード
     */
    public function setAddrState(mixed $addrState): static
    {
        if (is_null($addrState)) {
            throw new \InvalidArgumentException('non-nullable addrState cannot be null');
        }
        if (mb_strlen($addrState) > 3) {
            throw new \InvalidArgumentException('invalid length for $addrState when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 3.');
        }
        $this->container['addrState'] = $addrState;

        return $this;
    }

    /**
     * Gets addrCity.
     *
     * @return string|null
     */
    public function getAddrCity(): mixed
    {
        return $this->container['addrCity'];
    }

    /**
     * Sets addrCity.
     *
     * @param string $addrCity 上書き顧客（請求先） 住所の市区町村
     */
    public function setAddrCity(mixed $addrCity): static
    {
        if (is_null($addrCity)) {
            throw new \InvalidArgumentException('non-nullable addrCity cannot be null');
        }
        if (mb_strlen($addrCity) > 50) {
            throw new \InvalidArgumentException('invalid length for $addrCity when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 50.');
        }
        $this->container['addrCity'] = $addrCity;

        return $this;
    }

    /**
     * Gets addrLine1.
     *
     * @return string|null
     */
    public function getAddrLine1(): mixed
    {
        return $this->container['addrLine1'];
    }

    /**
     * Sets addrLine1.
     *
     * @param string $addrLine1 上書き顧客（請求先） 住所の町名・番地
     */
    public function setAddrLine1(mixed $addrLine1): static
    {
        if (is_null($addrLine1)) {
            throw new \InvalidArgumentException('non-nullable addrLine1 cannot be null');
        }
        if (mb_strlen($addrLine1) > 50) {
            throw new \InvalidArgumentException('invalid length for $addrLine1 when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 50.');
        }
        $this->container['addrLine1'] = $addrLine1;

        return $this;
    }

    /**
     * Gets addrLine2.
     *
     * @return string|null
     */
    public function getAddrLine2(): mixed
    {
        return $this->container['addrLine2'];
    }

    /**
     * Sets addrLine2.
     *
     * @param string $addrLine2 上書き顧客（請求先） 住所の建物名・部屋番号
     */
    public function setAddrLine2(mixed $addrLine2): static
    {
        if (is_null($addrLine2)) {
            throw new \InvalidArgumentException('non-nullable addrLine2 cannot be null');
        }
        if (mb_strlen($addrLine2) > 50) {
            throw new \InvalidArgumentException('invalid length for $addrLine2 when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 50.');
        }
        $this->container['addrLine2'] = $addrLine2;

        return $this;
    }

    /**
     * Gets addrLine3.
     *
     * @return string|null
     */
    public function getAddrLine3(): mixed
    {
        return $this->container['addrLine3'];
    }

    /**
     * Sets addrLine3.
     *
     * @param string $addrLine3 上書き顧客（請求先）住所 その他
     */
    public function setAddrLine3(mixed $addrLine3): static
    {
        if (is_null($addrLine3)) {
            throw new \InvalidArgumentException('non-nullable addrLine3 cannot be null');
        }
        if (mb_strlen($addrLine3) > 50) {
            throw new \InvalidArgumentException('invalid length for $addrLine3 when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 50.');
        }
        $this->container['addrLine3'] = $addrLine3;

        return $this;
    }

    /**
     * Gets addrPostCode.
     *
     * @return string|null
     */
    public function getAddrPostCode(): mixed
    {
        return $this->container['addrPostCode'];
    }

    /**
     * Sets addrPostCode.
     *
     * @param string $addrPostCode 上書き顧客（請求先） 住所の郵便番号
     */
    public function setAddrPostCode(mixed $addrPostCode): static
    {
        if (is_null($addrPostCode)) {
            throw new \InvalidArgumentException('non-nullable addrPostCode cannot be null');
        }
        if (mb_strlen($addrPostCode) > 16) {
            throw new \InvalidArgumentException('invalid length for $addrPostCode when calling InvoiceCreatingRequestCustomerOverwrite., must be smaller than or equal to 16.');
        }
        $this->container['addrPostCode'] = $addrPostCode;

        return $this;
    }

    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
