<?php

declare(strict_types=1);
/**
 * fincode API.
 *
 * fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Fincode\Model;

use OpenAPI\Fincode\ObjectSerializer;

/**
 * @implements \ArrayAccess<string, mixed>
 */
class InvoiceListRetrievingQueryParams implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    protected static string $openAPIModelName = 'Invoice.ListRetrieving.QueryParams';
    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = ['status' => 'string', 'keyword' => 'string', 'dueDateFrom' => 'string', 'dueDateTo' => 'string', 'issueDateFrom' => 'string', 'issueDateTo' => 'string', 'totalAmountMax' => 'float', 'totalAmountMin' => 'float', 'createdFrom' => 'string', 'createdTo' => 'string', 'customerId' => 'string', 'customerName' => 'string', 'invoiceNumber' => 'string', 'linesDateFrom' => 'string', 'linesDateTo' => 'string', 'transactionDateFrom' => 'string', 'transactionDateTo' => 'string', 'isUncollectible' => 'bool'];
    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = ['status' => null, 'keyword' => null, 'dueDateFrom' => null, 'dueDateTo' => null, 'issueDateFrom' => null, 'issueDateTo' => null, 'totalAmountMax' => null, 'totalAmountMin' => null, 'createdFrom' => null, 'createdTo' => null, 'customerId' => null, 'customerName' => null, 'invoiceNumber' => null, 'linesDateFrom' => null, 'linesDateTo' => null, 'transactionDateFrom' => null, 'transactionDateTo' => null, 'isUncollectible' => null];
    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = ['status' => false, 'keyword' => false, 'dueDateFrom' => false, 'dueDateTo' => false, 'issueDateFrom' => false, 'issueDateTo' => false, 'totalAmountMax' => false, 'totalAmountMin' => false, 'createdFrom' => false, 'createdTo' => false, 'customerId' => false, 'customerName' => false, 'invoiceNumber' => false, 'linesDateFrom' => false, 'linesDateTo' => false, 'transactionDateFrom' => false, 'transactionDateTo' => false, 'isUncollectible' => false];
    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array<string, string|null>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties.
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = ['status' => 'status', 'keyword' => 'keyword', 'dueDateFrom' => 'due_date_from', 'dueDateTo' => 'due_date_to', 'issueDateFrom' => 'issue_date_from', 'issueDateTo' => 'issue_date_to', 'totalAmountMax' => 'total_amount_max', 'totalAmountMin' => 'total_amount_min', 'createdFrom' => 'created_from', 'createdTo' => 'created_to', 'customerId' => 'customer_id', 'customerName' => 'customer_name', 'invoiceNumber' => 'invoice_number', 'linesDateFrom' => 'lines_date_from', 'linesDateTo' => 'lines_date_to', 'transactionDateFrom' => 'transaction_date_from', 'transactionDateTo' => 'transaction_date_to', 'isUncollectible' => 'is_uncollectible'];
    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var array<string, string>
     */
    protected static array $setters = ['status' => 'setStatus', 'keyword' => 'setKeyword', 'dueDateFrom' => 'setDueDateFrom', 'dueDateTo' => 'setDueDateTo', 'issueDateFrom' => 'setIssueDateFrom', 'issueDateTo' => 'setIssueDateTo', 'totalAmountMax' => 'setTotalAmountMax', 'totalAmountMin' => 'setTotalAmountMin', 'createdFrom' => 'setCreatedFrom', 'createdTo' => 'setCreatedTo', 'customerId' => 'setCustomerId', 'customerName' => 'setCustomerName', 'invoiceNumber' => 'setInvoiceNumber', 'linesDateFrom' => 'setLinesDateFrom', 'linesDateTo' => 'setLinesDateTo', 'transactionDateFrom' => 'setTransactionDateFrom', 'transactionDateTo' => 'setTransactionDateTo', 'isUncollectible' => 'setIsUncollectible'];
    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var array<string, string>
     */
    protected static array $getters = ['status' => 'getStatus', 'keyword' => 'getKeyword', 'dueDateFrom' => 'getDueDateFrom', 'dueDateTo' => 'getDueDateTo', 'issueDateFrom' => 'getIssueDateFrom', 'issueDateTo' => 'getIssueDateTo', 'totalAmountMax' => 'getTotalAmountMax', 'totalAmountMin' => 'getTotalAmountMin', 'createdFrom' => 'getCreatedFrom', 'createdTo' => 'getCreatedTo', 'customerId' => 'getCustomerId', 'customerName' => 'getCustomerName', 'invoiceNumber' => 'getInvoiceNumber', 'linesDateFrom' => 'getLinesDateFrom', 'linesDateTo' => 'getLinesDateTo', 'transactionDateFrom' => 'getTransactionDateFrom', 'transactionDateTo' => 'getTransactionDateTo', 'isUncollectible' => 'getIsUncollectible'];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }
    /**
     * Associative array for storing property values.
     *
     * @phpstan-var array<string, mixed>
     *
     * @psalm-var array<string, mixed>
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param array<string, mixed> $data Associated array of property values
     *                                   initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('keyword', $data ?? [], null);
        $this->setIfExists('dueDateFrom', $data ?? [], null);
        $this->setIfExists('dueDateTo', $data ?? [], null);
        $this->setIfExists('issueDateFrom', $data ?? [], null);
        $this->setIfExists('issueDateTo', $data ?? [], null);
        $this->setIfExists('totalAmountMax', $data ?? [], null);
        $this->setIfExists('totalAmountMin', $data ?? [], null);
        $this->setIfExists('createdFrom', $data ?? [], null);
        $this->setIfExists('createdTo', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('customerName', $data ?? [], null);
        $this->setIfExists('invoiceNumber', $data ?? [], null);
        $this->setIfExists('linesDateFrom', $data ?? [], null);
        $this->setIfExists('linesDateTo', $data ?? [], null);
        $this->setIfExists('transactionDateFrom', $data ?? [], null);
        $this->setIfExists('transactionDateTo', $data ?? [], null);
        $this->setIfExists('isUncollectible', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }
        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return list<string> invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];
        if (!is_null($this->container['keyword']) && mb_strlen($this->container['keyword']) > 150) {
            $invalidProperties[] = "invalid value for 'keyword', the character length must be smaller than or equal to 150.";
        }
        if (!is_null($this->container['keyword']) && mb_strlen($this->container['keyword']) < 1) {
            $invalidProperties[] = "invalid value for 'keyword', the character length must be bigger than or equal to 1.";
        }
        if (!is_null($this->container['dueDateFrom']) && mb_strlen($this->container['dueDateFrom']) > 10) {
            $invalidProperties[] = "invalid value for 'dueDateFrom', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['dueDateFrom']) && mb_strlen($this->container['dueDateFrom']) < 10) {
            $invalidProperties[] = "invalid value for 'dueDateFrom', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['dueDateTo']) && mb_strlen($this->container['dueDateTo']) > 10) {
            $invalidProperties[] = "invalid value for 'dueDateTo', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['dueDateTo']) && mb_strlen($this->container['dueDateTo']) < 10) {
            $invalidProperties[] = "invalid value for 'dueDateTo', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['issueDateFrom']) && mb_strlen($this->container['issueDateFrom']) > 10) {
            $invalidProperties[] = "invalid value for 'issueDateFrom', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['issueDateFrom']) && mb_strlen($this->container['issueDateFrom']) < 10) {
            $invalidProperties[] = "invalid value for 'issueDateFrom', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['issueDateTo']) && mb_strlen($this->container['issueDateTo']) > 10) {
            $invalidProperties[] = "invalid value for 'issueDateTo', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['issueDateTo']) && mb_strlen($this->container['issueDateTo']) < 10) {
            $invalidProperties[] = "invalid value for 'issueDateTo', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['createdFrom']) && mb_strlen($this->container['createdFrom']) > 10) {
            $invalidProperties[] = "invalid value for 'createdFrom', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['createdFrom']) && mb_strlen($this->container['createdFrom']) < 10) {
            $invalidProperties[] = "invalid value for 'createdFrom', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['createdTo']) && mb_strlen($this->container['createdTo']) > 10) {
            $invalidProperties[] = "invalid value for 'createdTo', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['createdTo']) && mb_strlen($this->container['createdTo']) < 10) {
            $invalidProperties[] = "invalid value for 'createdTo', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['customerId']) && mb_strlen($this->container['customerId']) > 60) {
            $invalidProperties[] = "invalid value for 'customerId', the character length must be smaller than or equal to 60.";
        }
        if (!is_null($this->container['customerId']) && mb_strlen($this->container['customerId']) < 1) {
            $invalidProperties[] = "invalid value for 'customerId', the character length must be bigger than or equal to 1.";
        }
        if (!is_null($this->container['customerName']) && mb_strlen($this->container['customerName']) > 384) {
            $invalidProperties[] = "invalid value for 'customerName', the character length must be smaller than or equal to 384.";
        }
        if (!is_null($this->container['customerName']) && mb_strlen($this->container['customerName']) < 1) {
            $invalidProperties[] = "invalid value for 'customerName', the character length must be bigger than or equal to 1.";
        }
        if (!is_null($this->container['invoiceNumber']) && mb_strlen($this->container['invoiceNumber']) > 30) {
            $invalidProperties[] = "invalid value for 'invoiceNumber', the character length must be smaller than or equal to 30.";
        }
        if (!is_null($this->container['invoiceNumber']) && mb_strlen($this->container['invoiceNumber']) < 1) {
            $invalidProperties[] = "invalid value for 'invoiceNumber', the character length must be bigger than or equal to 1.";
        }
        if (!is_null($this->container['linesDateFrom']) && mb_strlen($this->container['linesDateFrom']) > 10) {
            $invalidProperties[] = "invalid value for 'linesDateFrom', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['linesDateFrom']) && mb_strlen($this->container['linesDateFrom']) < 10) {
            $invalidProperties[] = "invalid value for 'linesDateFrom', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['linesDateTo']) && mb_strlen($this->container['linesDateTo']) > 10) {
            $invalidProperties[] = "invalid value for 'linesDateTo', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['linesDateTo']) && mb_strlen($this->container['linesDateTo']) < 10) {
            $invalidProperties[] = "invalid value for 'linesDateTo', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['transactionDateFrom']) && mb_strlen($this->container['transactionDateFrom']) > 10) {
            $invalidProperties[] = "invalid value for 'transactionDateFrom', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['transactionDateFrom']) && mb_strlen($this->container['transactionDateFrom']) < 10) {
            $invalidProperties[] = "invalid value for 'transactionDateFrom', the character length must be bigger than or equal to 10.";
        }
        if (!is_null($this->container['transactionDateTo']) && mb_strlen($this->container['transactionDateTo']) > 10) {
            $invalidProperties[] = "invalid value for 'transactionDateTo', the character length must be smaller than or equal to 10.";
        }
        if (!is_null($this->container['transactionDateTo']) && mb_strlen($this->container['transactionDateTo']) < 10) {
            $invalidProperties[] = "invalid value for 'transactionDateTo', the character length must be bigger than or equal to 10.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus(): mixed
    {
        return $this->container['status'];
    }

    /**
     * Sets status.
     *
     * @param string $status インボイス請求書のステータス       カンマ(,)区切りで複数指定も可能です。       - `DRAFT`: 下書き - `AWAITING_CUSTOMER_PAYMENT`: 支払い待ち - `PAID`: 支払い完了 - `CANCELED`: キャンセル済
     */
    public function setStatus(mixed $status): static
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets keyword.
     *
     * @return string|null
     */
    public function getKeyword(): mixed
    {
        return $this->container['keyword'];
    }

    /**
     * Sets keyword.
     *
     * @param string $keyword キーワード      指定した場合、請求書作成時に指定した client_field_1, client_field_2, client_field_3 のいずれかにおいて指定したワードが部分一致する請求データのみを取得します
     */
    public function setKeyword(mixed $keyword): static
    {
        if (is_null($keyword)) {
            throw new \InvalidArgumentException('non-nullable keyword cannot be null');
        }
        if (mb_strlen($keyword) > 150) {
            throw new \InvalidArgumentException('invalid length for $keyword when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 150.');
        }
        if (mb_strlen($keyword) < 1) {
            throw new \InvalidArgumentException('invalid length for $keyword when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 1.');
        }
        $this->container['keyword'] = $keyword;

        return $this;
    }

    /**
     * Gets dueDateFrom.
     *
     * @return string|null
     */
    public function getDueDateFrom(): mixed
    {
        return $this->container['dueDateFrom'];
    }

    /**
     * Sets dueDateFrom.
     *
     * @param string $dueDateFrom 支払期日範囲（開始）   形式： `yyyy/MM/dd`      指定した場合、支払期日が指定日以降である請求データのみを取得します
     */
    public function setDueDateFrom(mixed $dueDateFrom): static
    {
        if (is_null($dueDateFrom)) {
            throw new \InvalidArgumentException('non-nullable dueDateFrom cannot be null');
        }
        if (mb_strlen($dueDateFrom) > 10) {
            throw new \InvalidArgumentException('invalid length for $dueDateFrom when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($dueDateFrom) < 10) {
            throw new \InvalidArgumentException('invalid length for $dueDateFrom when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['dueDateFrom'] = $dueDateFrom;

        return $this;
    }

    /**
     * Gets dueDateTo.
     *
     * @return string|null
     */
    public function getDueDateTo(): mixed
    {
        return $this->container['dueDateTo'];
    }

    /**
     * Sets dueDateTo.
     *
     * @param string $dueDateTo 支払期日範囲（終了）   形式： `yyyy/MM/dd`      指定した場合、支払期日が指定日以前の請求データのみを取得します
     */
    public function setDueDateTo(mixed $dueDateTo): static
    {
        if (is_null($dueDateTo)) {
            throw new \InvalidArgumentException('non-nullable dueDateTo cannot be null');
        }
        if (mb_strlen($dueDateTo) > 10) {
            throw new \InvalidArgumentException('invalid length for $dueDateTo when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($dueDateTo) < 10) {
            throw new \InvalidArgumentException('invalid length for $dueDateTo when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['dueDateTo'] = $dueDateTo;

        return $this;
    }

    /**
     * Gets issueDateFrom.
     *
     * @return string|null
     */
    public function getIssueDateFrom(): mixed
    {
        return $this->container['issueDateFrom'];
    }

    /**
     * Sets issueDateFrom.
     *
     * @param string $issueDateFrom 発行日範囲（開始）   形式： `yyyy/MM/dd`      指定した場合、発行日が指定日以降である請求データのみを取得します
     */
    public function setIssueDateFrom(mixed $issueDateFrom): static
    {
        if (is_null($issueDateFrom)) {
            throw new \InvalidArgumentException('non-nullable issueDateFrom cannot be null');
        }
        if (mb_strlen($issueDateFrom) > 10) {
            throw new \InvalidArgumentException('invalid length for $issueDateFrom when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($issueDateFrom) < 10) {
            throw new \InvalidArgumentException('invalid length for $issueDateFrom when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['issueDateFrom'] = $issueDateFrom;

        return $this;
    }

    /**
     * Gets issueDateTo.
     *
     * @return string|null
     */
    public function getIssueDateTo(): mixed
    {
        return $this->container['issueDateTo'];
    }

    /**
     * Sets issueDateTo.
     *
     * @param string $issueDateTo 発行日の範囲指定（終了）   形式： `yyyy/MM/dd`      指定した場合、発行日が指定日以前の請求データのみを取得します
     */
    public function setIssueDateTo(mixed $issueDateTo): static
    {
        if (is_null($issueDateTo)) {
            throw new \InvalidArgumentException('non-nullable issueDateTo cannot be null');
        }
        if (mb_strlen($issueDateTo) > 10) {
            throw new \InvalidArgumentException('invalid length for $issueDateTo when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($issueDateTo) < 10) {
            throw new \InvalidArgumentException('invalid length for $issueDateTo when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['issueDateTo'] = $issueDateTo;

        return $this;
    }

    /**
     * Gets totalAmountMax.
     *
     * @return float|null
     */
    public function getTotalAmountMax(): mixed
    {
        return $this->container['totalAmountMax'];
    }

    /**
     * Sets totalAmountMax.
     *
     * @param float $totalAmountMax 合計金額範囲（上限）      指定した場合、合計金額が指定金額以下の請求データのみを取得します
     */
    public function setTotalAmountMax(mixed $totalAmountMax): static
    {
        if (is_null($totalAmountMax)) {
            throw new \InvalidArgumentException('non-nullable totalAmountMax cannot be null');
        }
        $this->container['totalAmountMax'] = $totalAmountMax;

        return $this;
    }

    /**
     * Gets totalAmountMin.
     *
     * @return float|null
     */
    public function getTotalAmountMin(): mixed
    {
        return $this->container['totalAmountMin'];
    }

    /**
     * Sets totalAmountMin.
     *
     * @param float $totalAmountMin 合計金額範囲（下限）      指定した場合、合計金額が指定金額以上の請求データのみを取得します
     */
    public function setTotalAmountMin(mixed $totalAmountMin): static
    {
        if (is_null($totalAmountMin)) {
            throw new \InvalidArgumentException('non-nullable totalAmountMin cannot be null');
        }
        $this->container['totalAmountMin'] = $totalAmountMin;

        return $this;
    }

    /**
     * Gets createdFrom.
     *
     * @return string|null
     */
    public function getCreatedFrom(): mixed
    {
        return $this->container['createdFrom'];
    }

    /**
     * Sets createdFrom.
     *
     * @param string $createdFrom 作成日範囲（開始）   形式： `yyyy/MM/dd`      指定した場合、作成日が指定日以降である請求データのみを取得します
     */
    public function setCreatedFrom(mixed $createdFrom): static
    {
        if (is_null($createdFrom)) {
            throw new \InvalidArgumentException('non-nullable createdFrom cannot be null');
        }
        if (mb_strlen($createdFrom) > 10) {
            throw new \InvalidArgumentException('invalid length for $createdFrom when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($createdFrom) < 10) {
            throw new \InvalidArgumentException('invalid length for $createdFrom when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['createdFrom'] = $createdFrom;

        return $this;
    }

    /**
     * Gets createdTo.
     *
     * @return string|null
     */
    public function getCreatedTo(): mixed
    {
        return $this->container['createdTo'];
    }

    /**
     * Sets createdTo.
     *
     * @param string $createdTo 作成日範囲（終了）   形式： `yyyy/MM/dd`      指定した場合、作成日が指定日以前の請求データのみを取得します
     */
    public function setCreatedTo(mixed $createdTo): static
    {
        if (is_null($createdTo)) {
            throw new \InvalidArgumentException('non-nullable createdTo cannot be null');
        }
        if (mb_strlen($createdTo) > 10) {
            throw new \InvalidArgumentException('invalid length for $createdTo when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($createdTo) < 10) {
            throw new \InvalidArgumentException('invalid length for $createdTo when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['createdTo'] = $createdTo;

        return $this;
    }

    /**
     * Gets customerId.
     *
     * @return string|null
     */
    public function getCustomerId(): mixed
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId.
     *
     * @param string $customerId 顧客ID      指定した場合、顧客IDが完全一致する請求データのみを取得します
     */
    public function setCustomerId(mixed $customerId): static
    {
        if (is_null($customerId)) {
            throw new \InvalidArgumentException('non-nullable customerId cannot be null');
        }
        if (mb_strlen($customerId) > 60) {
            throw new \InvalidArgumentException('invalid length for $customerId when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 60.');
        }
        if (mb_strlen($customerId) < 1) {
            throw new \InvalidArgumentException('invalid length for $customerId when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 1.');
        }
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets customerName.
     *
     * @return string|null
     */
    public function getCustomerName(): mixed
    {
        return $this->container['customerName'];
    }

    /**
     * Sets customerName.
     *
     * @param string $customerName 顧客名（請求先宛名）      指定した場合、顧客名が部分一致する請求データのみを取得します
     */
    public function setCustomerName(mixed $customerName): static
    {
        if (is_null($customerName)) {
            throw new \InvalidArgumentException('non-nullable customerName cannot be null');
        }
        if (mb_strlen($customerName) > 384) {
            throw new \InvalidArgumentException('invalid length for $customerName when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 384.');
        }
        if (mb_strlen($customerName) < 1) {
            throw new \InvalidArgumentException('invalid length for $customerName when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 1.');
        }
        $this->container['customerName'] = $customerName;

        return $this;
    }

    /**
     * Gets invoiceNumber.
     *
     * @return string|null
     */
    public function getInvoiceNumber(): mixed
    {
        return $this->container['invoiceNumber'];
    }

    /**
     * Sets invoiceNumber.
     *
     * @param string $invoiceNumber 請求番号      指定した場合、請求番号が一致する請求データのみを取得します
     */
    public function setInvoiceNumber(mixed $invoiceNumber): static
    {
        if (is_null($invoiceNumber)) {
            throw new \InvalidArgumentException('non-nullable invoiceNumber cannot be null');
        }
        if (mb_strlen($invoiceNumber) > 30) {
            throw new \InvalidArgumentException('invalid length for $invoiceNumber when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 30.');
        }
        if (mb_strlen($invoiceNumber) < 1) {
            throw new \InvalidArgumentException('invalid length for $invoiceNumber when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 1.');
        }
        $this->container['invoiceNumber'] = $invoiceNumber;

        return $this;
    }

    /**
     * Gets linesDateFrom.
     *
     * @return string|null
     */
    public function getLinesDateFrom(): mixed
    {
        return $this->container['linesDateFrom'];
    }

    /**
     * Sets linesDateFrom.
     *
     * @param string $linesDateFrom 取引日付範囲（開始）   形式： `yyyy/MM/dd`      指定した場合、「取引の日付」として入力した取引日が指定日以降の請求データのみを取得します
     */
    public function setLinesDateFrom(mixed $linesDateFrom): static
    {
        if (is_null($linesDateFrom)) {
            throw new \InvalidArgumentException('non-nullable linesDateFrom cannot be null');
        }
        if (mb_strlen($linesDateFrom) > 10) {
            throw new \InvalidArgumentException('invalid length for $linesDateFrom when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($linesDateFrom) < 10) {
            throw new \InvalidArgumentException('invalid length for $linesDateFrom when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['linesDateFrom'] = $linesDateFrom;

        return $this;
    }

    /**
     * Gets linesDateTo.
     *
     * @return string|null
     */
    public function getLinesDateTo(): mixed
    {
        return $this->container['linesDateTo'];
    }

    /**
     * Sets linesDateTo.
     *
     * @param string $linesDateTo 取引日範囲（終了）   形式： `yyyy/MM/dd`      指定した場合、「取引の日付」として入力した取引日が指定日以前の請求データのみを取得します
     */
    public function setLinesDateTo(mixed $linesDateTo): static
    {
        if (is_null($linesDateTo)) {
            throw new \InvalidArgumentException('non-nullable linesDateTo cannot be null');
        }
        if (mb_strlen($linesDateTo) > 10) {
            throw new \InvalidArgumentException('invalid length for $linesDateTo when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($linesDateTo) < 10) {
            throw new \InvalidArgumentException('invalid length for $linesDateTo when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['linesDateTo'] = $linesDateTo;

        return $this;
    }

    /**
     * Gets transactionDateFrom.
     *
     * @return string|null
     */
    public function getTransactionDateFrom(): mixed
    {
        return $this->container['transactionDateFrom'];
    }

    /**
     * Sets transactionDateFrom.
     *
     * @param string $transactionDateFrom 支払完了日範囲（開始）   形式： `yyyy/MM/dd`      指定した場合、支払い完了日が指定日以降の請求データのみを取得します
     */
    public function setTransactionDateFrom(mixed $transactionDateFrom): static
    {
        if (is_null($transactionDateFrom)) {
            throw new \InvalidArgumentException('non-nullable transactionDateFrom cannot be null');
        }
        if (mb_strlen($transactionDateFrom) > 10) {
            throw new \InvalidArgumentException('invalid length for $transactionDateFrom when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($transactionDateFrom) < 10) {
            throw new \InvalidArgumentException('invalid length for $transactionDateFrom when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['transactionDateFrom'] = $transactionDateFrom;

        return $this;
    }

    /**
     * Gets transactionDateTo.
     *
     * @return string|null
     */
    public function getTransactionDateTo(): mixed
    {
        return $this->container['transactionDateTo'];
    }

    /**
     * Sets transactionDateTo.
     *
     * @param string $transactionDateTo 支払完了日範囲（終了）   形式： `yyyy/MM/dd`      指定した場合、支払い完了日が指定日以前の請求データのみを取得します
     */
    public function setTransactionDateTo(mixed $transactionDateTo): static
    {
        if (is_null($transactionDateTo)) {
            throw new \InvalidArgumentException('non-nullable transactionDateTo cannot be null');
        }
        if (mb_strlen($transactionDateTo) > 10) {
            throw new \InvalidArgumentException('invalid length for $transactionDateTo when calling InvoiceListRetrievingQueryParams., must be smaller than or equal to 10.');
        }
        if (mb_strlen($transactionDateTo) < 10) {
            throw new \InvalidArgumentException('invalid length for $transactionDateTo when calling InvoiceListRetrievingQueryParams., must be bigger than or equal to 10.');
        }
        $this->container['transactionDateTo'] = $transactionDateTo;

        return $this;
    }

    /**
     * Gets isUncollectible.
     *
     * @return bool|null
     */
    public function getIsUncollectible(): mixed
    {
        return $this->container['isUncollectible'];
    }

    /**
     * Sets isUncollectible.
     *
     * @param bool $isUncollectible 回収困難マーク      - `true`: 回収困難マーク済の請求データのみを取得 - `false`: 回収困難マークの無い請求データのみを取得 - `null`: いずれも取得
     */
    public function setIsUncollectible(mixed $isUncollectible): static
    {
        if (is_null($isUncollectible)) {
            throw new \InvalidArgumentException('non-nullable isUncollectible cannot be null');
        }
        $this->container['isUncollectible'] = $isUncollectible;

        return $this;
    }

    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
